# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.21.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'This project is a collection of Odoo modules containing various
    data files that are too big to fit the official addons or the other Community
    projects.


    Such data files may include for example tax tables, lists of ZIP codes, official
    activity nomenclatures...


    This project is the continuation of OpenERP-Nomenclatures, which had a narrower
    scope limited to only official files provided by government agencies.'
repo_name: Community Data Files
repo_slug: community-data-files
repo_website: https://github.com/OCA/community-data-files
use_pyproject_toml: false
use_ruff: false

